[package]
name = "rustowl-core"
version = "0.1.0"
edition = "2021"

[dependencies]
models = { path = "../models" }
serde.workspace = true
serde_json.workspace = true
log.workspace = true
tokio.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
